repos:
  - repo: local
    hooks: []
      # - id: run-tests
      #  name: Run Backend Tests
      #  entry: bash -c "set -x && source ./venv/bin/activate && PYTHONPATH=$(pwd)/backend python3 -m unittest discover -s backend/tests -t backend -p 'test_*.py' -v"
      #  language: system
      #  pass_filenames: false
      #  verbose: true  # Show logs
default_language_version:
  python: python3.12  # Ensure Python version matches GitHub Actions (if desired)

