---
  name: Run Backend Tests
  
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12.3"
  
        - name: Install dependencies
          shell: bash
          run: |
            set -x
            python3.12 -m pip install --upgrade pip
            python3.12 -m pip install -r requirements.txt
  
        #- name: Run tests
        #  shell: bash
        #  env:
        #    PYTHONPATH: ${{ github.workspace }}/backend
        #  run: |
        #    set -x
        #    python3.12 -m unittest discover -s backend/tests -t backend -p "test_*.py" -v
